<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="BubbleSort_tests.TestBubbleSort-20171102113517" skipped="0" tests="4" time="0.015">
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_bubble_sort" time="0.000"/>
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_get_number_tosort" time="0.001"/>
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_get_number_tosort_exception" time="0.001"/>
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_to_proceed_sorting" time="0.014">
		<error message="test_to_proceed_sorting() takes exactly 1 argument (3 given)" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/asha/eclipse-workspace/MyApp/myappdev/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
TypeError: test_to_proceed_sorting() takes exactly 1 argument (3 given)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[[6, 7, 5, 4, 3, 2, 1]
[5, 7, 6, 4, 3, 2, 1]
[5, 6, 7, 4, 3, 2, 1]
[4, 6, 7, 5, 3, 2, 1]
[4, 5, 7, 6, 3, 2, 1]
[4, 5, 6, 7, 3, 2, 1]
[3, 5, 6, 7, 4, 2, 1]
[3, 4, 6, 7, 5, 2, 1]
[3, 4, 5, 7, 6, 2, 1]
[3, 4, 5, 6, 7, 2, 1]
[2, 4, 5, 6, 7, 3, 1]
[2, 3, 5, 6, 7, 4, 1]
[2, 3, 4, 6, 7, 5, 1]
[2, 3, 4, 5, 7, 6, 1]
[2, 3, 4, 5, 6, 7, 1]
[1, 3, 4, 5, 6, 7, 2]
[1, 2, 4, 5, 6, 7, 3]
[1, 2, 3, 5, 6, 7, 4]
[1, 2, 3, 4, 6, 7, 5]
[1, 2, 3, 4, 5, 7, 6]
[1, 2, 3, 4, 5, 6, 7]
Fully Sorted :[1, 2, 3, 4, 5, 6, 7]
Please Enter Int Value
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
